# Generated by Django 2.1.5 on 2020-04-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=2)),
                ('humidity', models.CharField(max_length=2)),
                ('power', models.CharField(max_length=2)),
            ],
        ),
    ]
