# Generated by Django 2.1.5 on 2020-04-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0002_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rules',
            name='power',
        ),
    ]
