# Generated by Django 2.1.5 on 2020-04-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0003_remove_rules_power'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rules',
        ),
    ]
