# Generated by Django 2.1.5 on 2020-04-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0005_rules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rules',
            new_name='Rule',
        ),
    ]
